# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Gerry's World
title: Gerry's World
email: gerry.chen@duke.edu
description: >- # this means to ignore newlines until "baseurl:"
  Gerry Chen's personal website - a collection of projects, activities, and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "gerry-chen.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  gchenfc
timezone: America/New_York

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - "_projects/Doodlebot/1xName.MOV"
  - "_projects/Doodlebot/fullMessage.MOV"
  - "_projects/Doodlebot/shortTest.MOV"
  - "_projects/*.MOV"
  - "_publications/Li2019MMSPCvehicle"

defaults:
  -
    scope:
      path: ""
    values:
      googleTagId: "UA-107206610-1"
      layout: "default"
      comments: false
  -
    scope:
      path: "studygroups"
    values:
      googleTagId: "UA-107206610-2"
      comments: true
  -
    scope:
      path: ""
      type: blog
    values:
      layout: "blogPost"
      stylesheets: "/css/blogPost.css"
      comments: true
  -
    scope:
      path: ""
      type: projects
    values:
      layout: projectPost
      stylesheets: "/css/projectPost.css"
      comments: true
  -
    scope:
      path: ""
      type: publications
    values:
      layout: publicationEntry
      stylesheets: "/css/publication.css"
      comments: true

collections:
  blog:
    output: true
  projects:
    output: true
  publications:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
