# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Gerry's World
title: Gerry's World
email: gchen328@gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
  Gerry Chen's personal website - a collection of projects, activities, and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "gerry-chen.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  gchenfc
timezone: America/New_York

# Build settings
markdown: kramdown
# kramdown: # use {% highlight <language> linenos %} ... {% endhighlight %} instead
#   syntax_highlighter_opts:
#     block:
#       line_numbers: true
plugins:
  - jekyll-feed

exclude:
  - "_projects/Doodlebot/1xName.MOV"
  - "_projects/Doodlebot/fullMessage.MOV"
  - "_projects/Doodlebot/shortTest.MOV"
  - "_projects/*.MOV"
  - "_publications/Li2019MMSPCvehicle"

defaults:
  -
    scope:
      path: ""
    values:
      googleTagId: "UA-107206610-1"
      layout: "default"
      comments: false
  -
    scope:
      path: "studygroups"
    values:
      googleTagId: "UA-107206610-2"
      comments: true
  -
    scope:
      path: ""
      type: blog
    values:
      layout: "blogPost"
      stylesheets: "/css/blogPost.css"
      comments: true
  -
    scope:
      path: ""
      type: projects
    values:
      layout: projectPost
      stylesheets: "/css/projectPost.css"
      comments: true
  -
    scope:
      path: ""
      type: publications
    values:
      layout: publicationEntry
      stylesheets: "/css/publication.css"
      comments: true

collections:
  blog:
    output: true
  projects:
    output: true
  publications:
    output: true
future: true

socials:
  - name:   "Twitter"
    link:   "https://twitter.com/intent/follow?screen_name=gchenfc"
    badge:  "https://img.shields.io/twitter/follow/gchenfc?style=social&label=Twitter"
  - name:   "Google Scholar"
    link:   "https://scholar.google.com/citations?user=JIrOb5QAAAAJ&hl=en"
    badge:  "https://img.shields.io/badge/Google Scholar-_-_?style=social&logo=googlescholar"
  - name:   "Github"
    link:   "https://github.com/gchenfc"
    badge:  "https://img.shields.io/github/stars/gchenfc?label=Github&style=social"
  - name:   "LinkedIn"
    link:   "https://www.linkedin.com/in/gerry-chen/"
    badge:  "https://img.shields.io/badge/Linkedin-_-_?style=social&logo=linkedin"
  - name:   "ORCID"
    link:   "https://orcid.org/0000-0002-1026-1760"
    badge:  "https://img.shields.io/badge/ORCiD-_-_?style=social&logo=orcid"
  - name:   "YouTube"
    link:   "https://www.youtube.com/channel/UCzSX_ITIX4dXFOWZ6XX5JBA"
    badge:  "https://img.shields.io/youtube/channel/views/UCzSX_ITIX4dXFOWZ6XX5JBA?label=Youtube&style=social"
  - name:   "Facebook"
    link:   "https://www.facebook.com/gchenfc"
    badge:  "https://img.shields.io/badge/Facebook-_-_?style=social&logo=facebook"
  - name:   "Instagram"
    link:   "https://www.instagram.com/very_merry_gerry/"
    badge:  "https://img.shields.io/badge/Instagram-_-_?style=social&logo=instagram"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
